language: php
 
cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: hhvm
  
notifications:
  email: false

before_install:
  - phpenv config-rm xdebug.ini || return 0
  - travis_retry composer self-update

install:
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - composer cs-check
